/** Tajweed rule name → color mapping, shared with the Bayaan mobile app. */
export const tajweedColors: Record<string, string> = {
  madda_necessary: "#BF0100",
  madda_obligatory_mottasel: "#FF3EAE",
  madda_obligatory_monfasel: "#FF3EAE",
  madda_permissible: "#F47215",
  madda_normal: "#C38A07",
  "custom-alef-maksora": "#C38A07",
  ghunnah: "#0CBF71",
  idgham_ghunnah: "#0CBF71",
  idgham_shafawi: "#0CBF71",
  ikhafa: "#0CBF71",
  ikhafa_shafawi: "#0CBF71",
  iqlab: "#0CBF71",
  qalaqah: "#57CFFF",
  tafkhim: "#0088C7",
  idgham_mutajanisayn: "#0088C7",
  idgham_mutaqaribayn: "#0088C7",
  idgham_wo_ghunnah: "#0088C7",
  slnt: "#AAAAAA",
  ham_wasl: "#AAAAAA",
  laam_shamsiyah: "#AAAAAA",
  silah: "#8A4FFF",
  minor: "#00A0A0",
  madd: "#0CBF71",
  tashil: "#29B6F6",
  ibdal: "#29B6F6",
  taghliz: "#1A46D0",
};
